export const TEXT_EN:{[key: string]: string } = {
  primerTitulo: 'Mis XV años',
  tNombres: 'Leah Maite',
  traduccion: 'Ver invitación en español',
  pCancion: 'Your browser does not support the audio element.',
  subTitulo: 'You are invited!',
  mensajeBienvenida1: 'There are moments in life that are important on their own, but sharing them with those we love the most turns them into unique and unforgettable memories.',
mensajeBienvenida2: 'With God’s blessing and the love my family has given me, I feel happy to reach this moment in my life;<br><br>Because you are part of my life, it is my wish that you share with me the joy of my fifteenth birthday...',
  mensajeBienvenida3: 'Cordially invites you to enjoy <br>this magical day with me.',
  soloFaltan: 'Countdown:',
  counterDias: 'Days',
  counterHoras: 'Hours',
  counterMinutos: 'Minutes',
  counterSeg: 'Seconds',
  //NOMBRE DE PADRES
  tituloInicialPadres: 'With the blessing of God',
  subTituloInicialPadres: 'and our parents',
  nomPadres: 'My Parents',
  textPadres: 'Thanks to God´s blessing and all the love my parents have given me, I have reached the moment when I will leave my childhood behind and begin this new chapter of my life.',
  nomPadrinos: 'My Godparents',
  textPadrinos: 'Godparents are not found, they are chosen with the heart — and my heart chose you both.',
  //FECHA Y BODA
  textFechaBoda: 'the event will be on Saturday',
  fechaBoda: 'December | 12 | 2026',
  //GUARDAR LA FECHA
  guardaFecha: 'Save the date',
  // CEREMONIA Y RECEPCIÓN
  tituloCeremonia: 'Celebration',
  direccionCeremonia: '<b>Mission San Fernando Rey de España</b><br>15151 San Fernando Mission Blvd, Mission Hills, CA 91345, United States',
  horaCeremonia: 'Time: 2:00 P.M.',
  ubicacion: 'SEE LOCATION',
  tituloRecepcion: 'Reception',
  textoInv: 'Valet Parking complementary',
  direccionRecepcion: '<b>The Landmark</b><br>10635 Woodman Ave, Mission Hills, CA 91345, United States',
  horaRecepcion: 'Time: 5:00 P.M.',
  //ITINERARIO
  titleTimeline: 'Timeline',
  timelinejpg: 'assets/timeline2.jpg',
  // VESTIMENTA O DRESS CODE
  tituloVestimenta: 'Dress Code',
  textoVestimentaUno: 'Formal Style',
  textoVestimentaDos: 'We kindly ask you to dress formally, reminding you that the color red is reserved exclusively for the birthday girl. Thank you for your understanding and affection!',
  // NUESTROS MOMENTOS
  tituloMomentos: 'Our Moments',
  textoMomentos: 'Help grow the memories of this special day. Scan the QR code to share your moments and be part of this beautiful celebration.',
  buttonMomentos: 'UPLOAD PHOTOS!',
  // REGALOS
  tituloRegalo: 'Gifts',
  subtituloRegalo: '<b>Cash<b>',
  textoRegaloUno: 'Cash gifts are always welcome but never <br>obligatory. All we ask is that you be here with us.',
  textoRegaloDos: 'No gifts are expected, your presence is more than enough! Should you wish to give, a monetary gift would be greatly appreciated.',
  // NO NIÑOS
  tituloKids: 'Important Note',
  textoKids: 'We love children and their joy always lights up our lives. However, for this special celebration, the event will be adults only. We appreciate your understanding.',
  // PASES
  tituloPases: 'PASSES',
  textoPasesUno: 'Are reserved for you',
  textoPasesDos: '2 seats in your honor.',
  //CONFIRMACIÓN DE ASISTENCIA
  tituloConfirmacion: 'Confirm Your <br>Attendance',
  textoConfirmacionUno: 'Please confirm your',
  textoConfirmacionDos: 'assistance as soon as possible.',
  textoConfirmacionTres: 'Contacta a los novios.',
  buttonConfirmacion: 'WhatsApp',
  buttonForms: 'CONFIRM',
  // CONFIRMACION
  mensaje_confirmado: 'RSVP',
  yaConfirAsistencia: 'You have already confirmed your attendance!',
  mensajeBienvenidaConfirm: 'We hope to have your presence. Please confirm your attendance before ',
  cantidadAsistentes: 'The number of seats that have been reserved for you is: ',
  alertCantidadAsis: 'Number of attendees',
  alertaPuedesConfirmarHasta: 'You can confirm up to',
  alertaMinimoConfirmaciones: 'Please enter at least one guest.',
  invitNoEspecificado: 'We noticed that the names of your guests weren\'t specified. We would greatly appreciate it if you could provide us with this information to help us maintain better control.',
  mesaAsignada: 'Your place is at table number:',
  NombreInvitadoInput: 'Guest name',
  botonConfirmacion: 'Confirm',
  totalInvitadosConfirmado: 'Guest count:',
  despedidaEsperamosVerte: 'We look forward to seeing you!',
  txtNoAsistencia: 'We’re sorry you can’t join us. We hope to see you very soon!',
  acompañantesAgregados: 'Added Companions:',
  totalInvitados: 'Total Guests:',
  debesIngresarInvitados: 'You must enter at least one guest',
  puedesConfirmar: 'You can confirm up to',
  invitadoConfirmacion: 'Guest',
  asistentesAgregados: 'Added companions:',
  teEsperamos: 'We look forward to seeing you!',
  sininvitadostxt: 'Please enter your first and last name, and the names of your companions if they will be attending with you.',
  asistiras: 'Can you attend?',
  siAsistire: 'Yes I will attend',
  noAsistira: 'I won´t attend',
  estasSeguro: 'Are you sure?',
  fechaConfirmacionCaducada: 'The deadline to confirm your attendance has passed!',
  fechaConfirmacionCaducadaDos: 'If you’d like, you can contact Andrea.',
  despedidaTxt: 'We hope to see you.',
  // DESPEDIDA
  tituloDespedida: 'With love,',
  DespedidaNombres: 'Valeria and Josué',
  // GLASMMY
  textoGlasmmy: 'Created with love by',
  glasmmy: 'GlasmmyDigital'

}
